name: Ci/CD APP

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .Net
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.104'
 
      - name: Restore dependencies
        run: dotnet restore Vpn-Client.Desktop/Vpn-Client.Desktop.csproj

        #Сборка под линукс
      - name: Build linux
        run: |
          dotnet publish Vpn-Client.Desktop/Vpn-Client.Desktop.csproj -c --Release -r linux-x64 --self-contained true -o ./publish-linux
          cd publish-linux && zip -r ../vpn-client-linux.zip . && cd ..

        #Сборка под виндовс
      - name: Build windows
        run: |
          dotnet publish Vpn-Client.Desktop/Vpn-Client.Desktop.csproj -c --Release -r win-x64 --self-contained true -o ./publish-windows
          cd publish-windows && zip -r ../vpn-client-windows.zip . && cd ..
        #Сохранение готовых файлов
      - name: Upload Artifaccts
        uses: actions/upload-artifact@v4
        with:
          name: vpn-client-builds
          path: |
            ./publish-linux/
            ./publish-windows/

        #Релизы
      - name: Create Release
        uses: softprops/action-gh-release@v3
        #проверка
        if: success() && github.ref == 'refs/heads/master'
        with:
          tag_name: latest
          name: Release latest
          body: |
            автоматическая сборка из ветки master
            версия $latest
          draft: false
          prerelease: false
          files: |
            ./vpn-client-linux.zip
            ./vpn-client-windows.zip
        env:
          GH_TOKEN: ${{ secrets.GUTHUB_TOKEN }}
